language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install

script:
  - vendor/bin/phpunit tests/

os:
  - linux

sudo: required

dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi